server:
  port: 10000
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://10.211.55.3:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
      username: root
      password: root
#      Nacos 注册中心
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
#        阿里云对象上传
#    alicloud:
#      access-key: LTAI4G6sWhsMNcDrwdR7mKck
#      secret-key: ODyHrcm0AuMLobxHWl4IWM2vsqnh65
#      oss:
#        endpoint: oss-cn-beijing.aliyuncs.com
  application:
    name: gulimall-product
    #日期格式化
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

mybatis-plus:
#  告诉Mybatis Plus 扫描哪里
  mapper-locations: classpath:/mapper/**/*.xml
#  主键自增！
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    com.atguigu.gulimall: debug


